// <auto-generated />
using MVClast.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVClast.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVClast.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "Math"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "Science"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Arabic"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "English"
                        });
                });

            modelBuilder.Entity("MVClast.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Student eName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ismaillia",
                            Age = 20,
                            DepartmentId = 1,
                            Email = "Ahmed.1222@example.com",
                            Name = "Ahmed Abdallah",
                            Password = "Ahmed1111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ismaillia",
                            Age = 16,
                            DepartmentId = 2,
                            Email = "Ali.1222@example.com",
                            Name = "Ali Ahmed",
                            Password = "Ali11112"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ismaillia",
                            Age = 16,
                            DepartmentId = 3,
                            Email = "Maya.1222@example.com",
                            Name = "Maya",
                            Password = "Maya111113"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ismaillia",
                            Age = 15,
                            DepartmentId = 4,
                            Email = "Omar.1222@example.com",
                            Name = "Omar",
                            Password = "Omar111123"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ismaillia",
                            Age = 13,
                            DepartmentId = 1,
                            Email = "Abdallah.1222@example.com",
                            Name = "Abdallah",
                            Password = "Abdallah111112"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ismaillia",
                            Age = 16,
                            DepartmentId = 2,
                            Email = "Hatem.1222@example.com",
                            Name = "Hatem",
                            Password = "Hatem111121"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ismaillia",
                            Age = 19,
                            DepartmentId = 3,
                            Email = "Wael.1222@example.com",
                            Name = "Wael",
                            Password = "Wael1111"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ismaillia",
                            Age = 18,
                            DepartmentId = 4,
                            Email = "Laila1222@example.com",
                            Name = "Laila",
                            Password = "Laila1111"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Ismaillia",
                            Age = 16,
                            DepartmentId = 1,
                            Email = "Fathy.1222@example.com",
                            Name = "Fathy",
                            Password = "Fathy1111"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Ismaillia",
                            Age = 15,
                            DepartmentId = 2,
                            Email = "Osama.1222@example.com",
                            Name = "Osama",
                            Password = "OSama1111"
                        });
                });

            modelBuilder.Entity("MVClast.Models.Student", b =>
                {
                    b.HasOne("MVClast.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVClast.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
